#!/usr/bin/env python3
"""Generate the pass-through parts of the sswrap opengl32.dll proxy.

Every export of the real opengl32.dll gets an entry in g_real[] (filled at load time
from the real DLL). Exports that sswrap does not hook become a one-instruction thunk
(jmp through g_real[i]), so they cost nothing. Hooked exports are implemented in C.
"""
names = [n.strip() for n in open("exports.txt") if n.strip()]

# name -> stdcall argument bytes, for the exports implemented in sswrap.c
HOOKED = {
    "wglSwapBuffers": 4, "wglMakeCurrent": 8, "wglCreateContext": 4,
    "wglDeleteContext": 4, "wglGetProcAddress": 4,
    "glViewport": 16, "glScissor": 16, "glDrawBuffer": 4, "glReadBuffer": 4,
    "glGetIntegerv": 8, "glLineWidth": 4, "glPointSize": 4,
    "glReadPixels": 28, "glCopyPixels": 20, "glDrawPixels": 20, "glBitmap": 28,
    "glCopyTexImage2D": 32, "glCopyTexSubImage2D": 32,
    # post-processing: detect the 3D -> 2D HUD switch and capture the 3D projection
    "glMatrixMode": 4, "glLoadIdentity": 0, "glOrtho": 48,
    "glFrustum": 48, "glLoadMatrixf": 4, "glLoadMatrixd": 4, "glMultMatrixf": 4, "glMultMatrixd": 4,
}
missing = set(HOOKED) - set(names)
assert not missing, missing

with open("gl_names.h", "w") as f:
    f.write("/* generated by gen.py */\n#define GL_EXPORT_COUNT %d\n" % len(names))
    f.write("static const char *const g_names[GL_EXPORT_COUNT] = {\n")
    f.writelines('  "%s",\n' % n for n in names)
    f.write("};\n")
    for i, n in enumerate(names):
        f.write("#define IDX_%s %d\n" % (n, i))

with open("thunks.S", "w") as f:
    f.write("/* generated by gen.py */\n.text\n")
    for i, n in enumerate(names):
        if n in HOOKED:
            continue
        f.write(".globl _th_%s\n_th_%s:\n\tjmp *_g_real+%d\n" % (n, n, i * 4))

with open("opengl32.def", "w") as f:
    f.write("LIBRARY opengl32.dll\nEXPORTS\n")
    for n in names:
        if n in HOOKED:
            f.write("  %s=hk_%s@%d\n" % (n, n, HOOKED[n]))
        else:
            f.write("  %s=th_%s\n" % (n, n))

print("exports:", len(names), "hooked:", len(HOOKED))
